[[constraint]]
  branch = "master"
  name = "github.com/kubicorn/kubicorn"

[[constraint]]
  branch = "master"
  name = "github.com/marcwickenden/auger"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "go.etcd.io/etcd"
  version = "3.3.10"

[[constraint]]
  version = "7.0.0"
  name = "k8s.io/client-go"

[prune]
  go-tests = true
  unused-packages = true
